stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw_data
  pre_processing:
    cmd: python src/data_prep.py
    deps:
    - data/raw_data
    - src/data_prep.py
    outs:
    - data/processed
